# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
  body_converter:
    enabled: true
  param_fetcher_listener: true
  # si la valeur est à  force, nous sommes en mesure de recevoir les paramètres directement par leur nom
  allowed_methods_listener: true
  #  routing_loader: false
  view:
    formats: { json: true, xml: false, rss: false }
    mime_types:
      json:
        [
          "application/json",
          "application/json;version=1.0",
          "application/json;version=2.0",
        ]
  serializer:
    serialize_null: true
  # serialize_null si l'attribut est null il sera quand même sérialisé; donc true ici
  #  exception:
  #    codes:
  #      App\Exception\MyException: 403
  #    messages:
  #      App\Exception\MyException: Forbidden area.
  #format_listener:
  #  rules:
  #    - {
  #        path: ^/api,
  #        prefer_extension: true,
  #        fallback_format: json,
  #        priorities: [json, html],
  #      }
  versioning:
    enabled: true
    resolvers:
      media_type: # Accept header
        enabled: true
        regex: '/(v|version)=(?P<version>[0-9\.]+)/'
