#app/config/config.yml

fos_rest:
  body_converter:
    enabled: true
  view:
    formats: { json: true, xml: false, rss: false }
  serializer:
    serialize_null: true

sensio_framework_extra:
  view: { annotations: false }
