#app/config/config.yml

fos_rest:
  body_converter:
    enabled: true
  view:
    formats: { json: true, xml: false, rss: false }
  serializer:
    serialize_null: true
# serialize_null si l'attribut est null il sera quand même sérialisé; donc true ici

sensio_framework_extra:
  view: { annotations: false }
